version: "3"
services:
  nginx:
    image: nginx:alpine
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "${NGINX_HTTP_PORT-8080}:80"
    depends_on:
      - php-fpm

  php-fpm:
    build: .
    volumes:
      - .:/var/www
    depends_on:
      - mysql

  mysql:
    image: mysql
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: webdev
